
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fachive
    username: root
    password: 84948494
  jpa:
    database: mysql   # 추가 해준 부분
    hibernate:
      ddl-auto: update  # 스키마 자동 생성
    show-sql: true      # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # SQL pretty print